name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Or 'main' depending on your branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Create .env.production for Vite
        run: |
          echo "VITE_API_URL=https://savorly-backend-c6hu.onrender.com" >> frontend/savorly-frontend/.env.production
          echo "VITE_CLIENT_URL=https://elizbeh.github.io/savorly-frontend" >> frontend/savorly-frontend/.env.production

      - name: Install dependencies
        run: npm install
        working-directory: frontend/savorly-frontend

      - name: Build app
        run: npm run build
        working-directory: frontend/savorly-frontend

      - name: Deploy to GitHub Pages
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run deploy
        working-directory: frontend/savorly-frontend
